# Generated by Django 2.2.6 on 2019-11-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Foto'),
        ),
    ]
